[package]
name = "tja"
version = "0.1.0"
edition = "2024"

[lib]
name = "tja"
path = "src/lib.rs"

[dependencies]
derive_more = { version = "2.0.1", features = ["from", "display"] }
impl_ops = "0.1.1"
paste = "1.0.15"
